version: "3.8"

services:
  db:
    image: postgres:12
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./sql:/sql/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    env_file:
      - ./.env
    ports:
      - 5432:5432
  redis:
    image: redis:alpine
  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - 8000:8000
    environment:
      - DJANGO_DEBUG='True'
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - REDIS_URL=redis://redis
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
    depends_on:
      - db
      - redis
  bot:
    build: .
    command: python run_polling.py
    environment:
      - DJANGO_DEBUG='True'
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - REDIS_URL=redis://redis
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
    depends_on:
      - web
  celery:
    build: .
    command: celery -A conf worker --loglevel=INFO
    volumes:
      - .:/code
    environment:
      - DJANGO_DEBUG='True'
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - REDIS_URL=redis://redis
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - SUBSCRIPTION_UPDATE_PERIOD_SECONDS=${SUBSCRIPTION_UPDATE_PERIOD_SECONDS}
    depends_on:
      - redis
      - web
  celery-beat:
    build: .
    command: celery -A conf beat --loglevel=INFO
    volumes:
      - .:/code
    environment:
      - DJANGO_DEBUG='True'
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - REDIS_URL=redis://redis
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - SUBSCRIPTION_UPDATE_PERIOD_SECONDS=${SUBSCRIPTION_UPDATE_PERIOD_SECONDS}
    depends_on:
      - redis
      - celery
      - web

volumes:
  postgres_data: